setTimeout(()=>{
    document.write("10<br>");
    setTimeout(()=>{
        document.write("9<br>");
        setTimeout(()=>{
            document.write("8<br>");
            setTimeout(()=>{
                document.write("7<br>");
                setTimeout(()=>{
                    document.write("6<br>");
                    setTimeout(()=>{
                        document.write("5<br>");
                        setTimeout(()=>{
                            document.write("3<br>");
                            setTimeout(()=>{
                                document.write("2<br>");
                                setTimeout(()=>{
                                    document.write("1<br>");
                                    setTimeout(()=>{
                                        document.write("TASK DONE");
},3000);
},3000);
},3000);
},3000);
},3000);
},3000);
},3000);
},3000);
},3000);
},3000);